name: Pylint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Pylint
        run: |
          pip install pylint
      - name: Code Review Scoring
        run: |
          find . -name '*.py' -not -path './.venv/*' -print -exec pylint {} \;
      - name: Analysing the code with Pylint
        run: |
          pylint $(find . -name '*.py' -not -path './.venv/*') --fail-under=8.0
